# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dataPublicacao', models.DateField(null=True)),
                ('autor', models.CharField(blank=True, max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('tipoLivro', models.PositiveSmallIntegerField(choices=[(1, 'Capa Dura'), (2, 'Simples'), (3, 'E-book')])),
            ],
        ),
    ]
