# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('dataPublicacao', models.DateField(null=True, verbose_name='Data de Publicação')),
                ('autor', models.CharField(blank=True, max_length=30, verbose_name='Autor')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('paginas', models.IntegerField(blank=True, null=True, verbose_name='Qntd. de Páginas')),
                ('tipoLivro', models.PositiveSmallIntegerField(choices=[(1, 'Capa Dura'), (2, 'Simples'), (3, 'E-book')], verbose_name='Tipo de Livro')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
                'ordering': ['titulo'],
            },
        ),
    ]
